"""Charta Python SDK — typed chart schemas and API client."""

from charta.models import (
    ChartInput,
    ChartResult,
    ChartStyle,
    ChartType,
    DataPoint,
    BarData,
    GroupedBarData,
    StackedBarData,
    WaterfallData,
    LineData,
    AreaData,
    PieData,
    DonutData,
    ScatterData,
    BubbleData,
    GanttData,
    MekkoData,
    RadarData,
    HeatmapData,
    BarChart,
    GroupedBarChart,
    StackedBarChart,
    WaterfallChart,
    LineChart,
    AreaChart,
    PieChart,
    DonutChart,
    ScatterChart,
    BubbleChart,
    GanttChart,
    MekkoChart,
    RadarChart,
    HeatmapChart,
)
from charta.client import AsyncChartaClient, ChartaClient

__version__ = "1.1.0"

__all__ = [
    # Core types
    "ChartType",
    "ChartStyle",
    "DataPoint",
    "ChartInput",
    "ChartResult",
    # Typed data points per chart type
    "BarData",
    "GroupedBarData",
    "StackedBarData",
    "WaterfallData",
    "LineData",
    "AreaData",
    "PieData",
    "DonutData",
    "ScatterData",
    "BubbleData",
    "GanttData",
    "MekkoData",
    "RadarData",
    "HeatmapData",
    # Typed chart inputs per chart type
    "BarChart",
    "GroupedBarChart",
    "StackedBarChart",
    "WaterfallChart",
    "LineChart",
    "AreaChart",
    "PieChart",
    "DonutChart",
    "ScatterChart",
    "BubbleChart",
    "GanttChart",
    "MekkoChart",
    "RadarChart",
    "HeatmapChart",
    # Client
    "ChartaClient",
    "AsyncChartaClient",
]
